### ISSUE TITLE
Life cycle and separating different scopes (1-3) from EXIOBASE

### ISSUE THREAD

**Issue by erm-akif** [IndEcol/pymrio#109]
Hi @konstantinstadler I have 2 questions

1. Whats the Life cycle covered by EXIOBASE, is it Cradle to Gate or Cradle to grave, because Use phase clearly lacks from the inventory

 2. Is there a any feasible way to separate the emission scopes (1-3) from EXIOBASE?

**Comment by konstantinstadler** [comment]
This are exiobase specific questios - please reach out to [exiobase-support@googlegroups.com](mailto:exiobase-support@googlegroups.com)
