### ISSUE TITLE
Potential typos in Exiobase3 industry names

### ISSUE THREAD

**Issue by dailylifeofwei** [IndEcol/pymrio#123]
I am not sure this is the right place to raise the issue. But it looks there are potential typos in some industry names in Exiobase3 (v.3.8.2). Here are a few examples:
'Re-processing of secondary preciuos metals into new preciuos metals'
'Sale, maintenance, repair of motor vehicles, motor vehicles parts, motorcycles, motor cycles parts and accessoiries"
'Biogasification of sewage slugde, incl. land application'

**Comment by konstantinstadler** [comment]
Yep, but as some people use the strings for matching it would break if we fix that. We will consider that for the next exiobase version
