### ISSUE TITLE
Ghosh implementation for downstream scope 3

### ISSUE THREAD

**Issue by Beckebanze** [IndEcol/pymrio#135]
The current pymrio has all relevant matrices related the Leontief attribution model implemented. This can be used to calculate the factors of production that are used as input to a sector or product, covering the upstream indirect inputs, also referred to as upstream scope 3. The scope 3 of a sector also includes a downstream component, which consists of the factors of production associated with the sector's input to other sectors. An attribution methodology that covers this so-called downstream scope 3 is the Ghosh model. Mathematically, there are many similarities between the Ghosh and Leontief models, and it thus makes sense to implement Ghosh in analogy with Leontief.

The proposal is to 
* implement the equivalent of A for Ghosh (often referred to A* in literature)
* implement the Ghosh inverse (often referred to G in literature)
* implement the downstream scope 3 multiplier, M_{down}, such the sum of the M+M_{down} is the full scope multiplier, with M the existing multiplier in pymrio that covers scope 1,2&3 upstream.
* a short addition to the pymrio background page that introduces the Ghosh model
* tests that test the functionality of the added functions

**Comment by konstantinstadler** [comment]
That would be a fantastic contribution. I would love to add this to pymrio and happy to receive a pull request for this
